services:
  frontend:
    image: rhkd4129/frontend:latest
    ports:
      - "80:80"
    restart: always

  backend:
    image: rhkd4129/backend:latest
    ports:
      - "8085:8085"
    restart: always
    depends_on:
      - oracle-db
      - redis-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle-db:1521/xe
      SPRING_DATASOURCE_USERNAME: MYPROJECT
      SPRING_DATASOURCE_PASSWORD: tiger2
      SPRING_REDIS_HOST: redis-db
      SPRING_REDIS_PORT: 6379

  oracle-db:
    image: gvenzl/oracle-xe:11
    ports:
      - "1521:1521"
    restart: always
    environment:
      ORACLE_PASSWORD: oracle
    volumes:
      - oracle_data:/opt/oracle/oradata

  redis-db:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: always

volumes:
  oracle_data:
