services:
  frontend:
    image: rhkd4129/frontend:latest
    ports:
      - "80:80"
    restart: always

  backend:
    image: rhkd4129/backend:latest
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - oracle
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle:1521/XE
      SPRING_DATASOURCE_USERNAME: MYPROJECT
      SPRING_DATASOURCE_PASSWORD: tiger2
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

  oracle:
    image: gvenzl/oracle-xe:11
    ports:
      - "1521:1521"
    restart: always
    environment:
      ORACLE_PASSWORD: oracle
    volumes:
      - oracle_data:/opt/oracle/oradata

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: always

volumes:
  oracle_data:
