# spring.application.name=second
server:
  port: 8085

fastapi:
  url: http://localhost:8084

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      location: C:\Server\PDF\
      enabled: true

  jpa:
    hibernate:
      ddl-auto: none
#      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        default_batch_fetch_size: 500
        format_sql: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        type: trace
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/orcl
#    url: jdbc:oracle:thin:@localhost:1521/xe
    username: MYPROJECT
    password: tiger2
#  security:
#    oauth2:
#      client:
#        registration:
#          google:  # 예시로 Google OAuth2를 사용한다고 가정
#            client-name: google
#            scope: profile,email
#            client-id: 205208599167-lbc3nd1hut7mg5qmspc3hr8ppu1e16dp.apps.googleusercontent.com
#            client-secret: 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
#            redirect-uri: http://localhost:8084/login/oauth2/code/google
  #            authorization-grant: authorization_code
#  data:
#    redis:
#      host: localhost
#      port: 6379
#      database: 0
#      timeout: 3000
#      client-type: lettuce
#      lettuce:
#        pool:
#          max-active: 8
#          max-idle: 8
#          min-idle: 2
#          max-wait: -1

