# spring.application.name=second
server:
  port: 8085

fastapi:
  url: http://localhost:8084

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    #    url: jdbc:oracle:thin:@localhost:1521/orcl
    username: MYPROJECT
    password: tiger2



  jpa:
    hibernate:
      ddl-auto: none
    #      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        default_batch_fetch_size: 500
        format_sql: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        type: trace
cloud:
  aws:
#    credentials:
#      access-key: hi
#      secret-key: hi
    region:
      static: ap-northeast-2   # 서울 리전
    s3:
      bucket: toyproject-lee
      key-prefix: pdf/


