# spring.application.name=second
server:
  port: 8085

fastapi:
  url: http://api-server:8084

sse:
  event:
    pdf-complete: "${SSE_EVENT_PDF_COMPLETE:pdf완료}"
    connect:      "${SSE_EVENT_CONNECT:connect}"

redis:
  stream:
    pdf-events:  "${REDIS_STREAM_PDF_EVENTS:pdf:events}"
    pdf-results: "${REDIS_STREAM_PDF_RESULTS:pdf:results}"

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      location: /app/pdf

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    # EC2 생성 후 내부 IP로 교체 필요
#    url: jdbc:oracle:thin:@EC2_INTERNAL_IP:1521/xe
    url: jdbc:oracle:thin:@oracle-db:1521/xe
    username: MYPROJECT
    password: tiger2

  data:
    redis:
      host: redis-db
      port: 6379
      database: 0
      timeout: 30000
      client-type: lettuce
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: -1



  jpa:
    hibernate:
      #ddl-auto: none
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        default_batch_fetch_size: 500
        format_sql: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        type: trace
cloud:
  aws:
    # EC2 IAM Role 적용으로 액세스 키 불필요 → 제거
    # credentials:
    #   access-key: ${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
    #   secret-key: ${CLOUD_AWS_CREDENTIALS_SECRET_KEY}
    region:
      static: ap-northeast-2   # 서울 리전
    s3:
      bucket: toyproject-lee
      key-prefix: pdf/
      result-key-prefix: xlsx/


