name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: Docker Hub 로그인
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: 이미지 빌드 & 푸시
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

      - name: EC2에서 pull & 실행
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 43.200.234.146
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            export CLOUD_AWS_CREDENTIALS_ACCESS_KEY="${{ secrets.AWS_ACCESS_KEY_ID }}"
            export CLOUD_AWS_CREDENTIALS_SECRET_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
            docker-compose pull
            docker-compose up -d
            

      # 빌드된 jar 파일을 EC2로 전송
#      - name: EC2에 jar 파일 업로드
#        uses: appleboy/scp-action@v0.1.7
#        with:
#          host: ${{ secrets.EC2_HOST }}
#          username: ${{ secrets.EC2_USER }}
#          key: ${{ secrets.EC2_KEY }}
#          source: './backend/build/libs/*.jar'
#          target: '/home/${{ secrets.EC2_USER }}/app'
#          strip_components: 3  # backend/build/libs/ 경로 제거하고 jar만 복사
#
#      # EC2 접속 후 기존 프로세스 종료 → 새 jar 실행
#      - name: EC2에서 앱 재시작
#        uses: appleboy/ssh-action@v1.0.3
#        with:
#          host: ${{ secrets.EC2_HOST }}
#          username: ${{ secrets.EC2_USER }}
#          key: ${{ secrets.EC2_KEY }}
#          script: |
#            PID=$(pgrep -f '*.jar' || true)
#            if [ -n "$PID" ]; then
#              kill -15 $PID
#              sleep 3
#            fi
#
#            cd /home/${{ secrets.EC2_USER }}/app
#            JAR_FILE=$(ls *.jar | tail -1)
#            nohup java -jar $JAR_FILE \
#              --spring.profiles.active=prod \   ← 이거 추가
#              > app.log 2>&1 &
