name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: Docker Hub 로그인
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: 이미지 빌드 & 푸시
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

      - name: EC2에서 pull & 실행
        uses: appleboy/ssh-action@v1.0.3
#        ssh -i EC2_KEY ec2-user@43.200.234.146 "docker-compose pull && docker-compose up -d"
        with:
          host: 43.200.234.146
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker-compose pull
            docker-compose up -d



      - name: 의존성 설치
        working-directory: ./frontend
        run: npm install

      - name: 빌드 실행
        working-directory: ./frontend
        run: npm run build
#      - name: dist 폴더를 EC2로 전송
#        uses: appleboy/scp-action@v0.1.7
#        with:
#          host: 43.200.234.146
#          username: ec2-user
#          key: ${{ secrets.EC2_KEY }}
#          source: ./frontend/dist/
#          target: /home/ec2-user/dist-deploy
#          strip_components: 2
#
#      - name: EC2 nginx 경로로 파일 이동
#        uses: appleboy/ssh-action@v1.0.3
#        with:
#          host: 43.200.234.146
#          username: ec2-user
#          key: ${{ secrets.EC2_KEY }}
#          script: |
#            sudo rm -rf /usr/share/nginx/html/*
#            sudo cp -r /home/ec2-user/dist-deploy/dist/* /usr/share/nginx/html/
#            rm -rf /home/ec2-user/dist-deploy


#      - name: AWS 자격증명 설정
#        uses: aws-actions/configure-aws-credentials@v2
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: ${{ secrets.AWS_REGION }}
#
#      - name: S3에 빌드 파일 업로드
#        working-directory: ./frontend
#        run: |
#          aws s3 sync ./dist s3://${{ secrets.S3_BUCKET_NAME }} \
#            --delete
#
#      - name: CloudFront 캐시 무효화
#        run: |
#          aws cloudfront create-invalidation \
#            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
#            --paths "/*"

      # run: 실제 쉘 명령어 실행 (터미널에서 치는 것과 동일)
      # uses: 이미 만들어진 GitHub Action 사용
      # checkout: 현재 레포지토리 코드를 서버로 clone 해옴  이거 없으면 코드가 없어서 build 불가
      # with: 해당 action에 옵션 전달
      # working-directory: 해당 경로에서 명령어 실행
